### ISSUE TITLE
Improve logging configuration and detail

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#356]
This is an umbrella issue for a handful of sub-tasks and for the tasks that fall in between them.

- [ ] #87: While running tests, log to `test.log` file instead of console 
- [ ] #233: Replace PM2 log symlinking with proper configuration
- [ ] #248: Make sure we can inspect the app using yarn tasks in production (since currently, tasks like `yarn queue:jobs:list` aren't usable in production due to console output suppression)
- [ ] #329: Dump old logs to S3 instead of losing them
- [ ] #35: Add Slack as an error logger transport
